// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwu_cojPHhbI8VYnVgINRuolwcbDXEQY',
    appId: '1:670966326779:web:a5e6e7e12d1eb085c6975e',
    messagingSenderId: '670966326779',
    projectId: 'cmsc23-project-46270',
    authDomain: 'cmsc23-project-46270.firebaseapp.com',
    storageBucket: 'cmsc23-project-46270.appspot.com',
    measurementId: 'G-CJNLKEDS3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfRUf_S1PbDhFFhLYKIUP7bADdVr6JORw',
    appId: '1:670966326779:android:9f6d1aa10b9154edc6975e',
    messagingSenderId: '670966326779',
    projectId: 'cmsc23-project-46270',
    storageBucket: 'cmsc23-project-46270.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8FX0UgWxOakFjZPsj5nyLKiHGmAklIc',
    appId: '1:670966326779:ios:983f955c52744d5fc6975e',
    messagingSenderId: '670966326779',
    projectId: 'cmsc23-project-46270',
    storageBucket: 'cmsc23-project-46270.appspot.com',
    iosBundleId: 'com.example.elbigayan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8FX0UgWxOakFjZPsj5nyLKiHGmAklIc',
    appId: '1:670966326779:ios:983f955c52744d5fc6975e',
    messagingSenderId: '670966326779',
    projectId: 'cmsc23-project-46270',
    storageBucket: 'cmsc23-project-46270.appspot.com',
    iosBundleId: 'com.example.elbigayan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtwu_cojPHhbI8VYnVgINRuolwcbDXEQY',
    appId: '1:670966326779:web:eb4076ca5602115cc6975e',
    messagingSenderId: '670966326779',
    projectId: 'cmsc23-project-46270',
    authDomain: 'cmsc23-project-46270.firebaseapp.com',
    storageBucket: 'cmsc23-project-46270.appspot.com',
    measurementId: 'G-2MXMJNKKFC',
  );
}
